ALTER TABLE exams
    MODIFY id VARCHAR(64) NOT NULL COMMENT '考试ID',
    MODIFY title VARCHAR(200) NOT NULL COMMENT '考试标题',
    MODIFY status VARCHAR(32) NOT NULL COMMENT '考试状态',
    MODIFY start_at TIMESTAMP(6) NOT NULL COMMENT '考试允许开始时间',
    MODIFY end_at TIMESTAMP(6) NOT NULL COMMENT '考试关闭时间',
    MODIFY duration_minutes INT NOT NULL COMMENT '考试作答时长，单位分钟',
    MODIFY paper_id VARCHAR(64) NOT NULL COMMENT '关联试卷ID',
    MODIFY created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    MODIFY updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    MODIFY version BIGINT NOT NULL DEFAULT 1 COMMENT '乐观锁版本',
    COMMENT = '考试基础信息表';

ALTER TABLE exam_candidates
    MODIFY id VARCHAR(140) NOT NULL COMMENT '考试考生分配ID',
    MODIFY exam_id VARCHAR(64) NOT NULL COMMENT '考试ID',
    MODIFY candidate_id VARCHAR(64) NOT NULL COMMENT '考生ID',
    MODIFY created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    COMMENT = '考试与考生分配关系表';

ALTER TABLE papers
    MODIFY id VARCHAR(64) NOT NULL COMMENT '试卷ID',
    MODIFY title VARCHAR(200) NOT NULL COMMENT '试卷标题',
    MODIFY assigned_at TIMESTAMP(6) NOT NULL COMMENT '试卷分配时间',
    MODIFY created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    MODIFY updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    MODIFY version BIGINT NOT NULL DEFAULT 1 COMMENT '乐观锁版本',
    COMMENT = '已分配试卷表';

ALTER TABLE paper_questions
    MODIFY id VARCHAR(140) NOT NULL COMMENT '试卷题目关系ID',
    MODIFY paper_id VARCHAR(64) NOT NULL COMMENT '试卷ID',
    MODIFY question_version_id VARCHAR(64) NOT NULL COMMENT '题目版本ID',
    MODIFY question_order INT NOT NULL COMMENT '题目在试卷中的顺序',
    MODIFY created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    COMMENT = '试卷题目关系表';

ALTER TABLE questions
    MODIFY version_id VARCHAR(64) NOT NULL COMMENT '题目版本ID',
    MODIFY question_id VARCHAR(64) NOT NULL COMMENT '题目业务ID',
    MODIFY type VARCHAR(32) NOT NULL COMMENT '题型',
    MODIFY prompt TEXT NOT NULL COMMENT '题干',
    MODIFY points INT NOT NULL COMMENT '分值',
    MODIFY max_length INT NULL COMMENT '简答题最大输入长度',
    MODIFY correct_option_id VARCHAR(64) NULL COMMENT '单选题正确选项ID',
    MODIFY reference_answer TEXT NULL COMMENT '简答题参考答案',
    MODIFY created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    MODIFY updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    MODIFY version BIGINT NOT NULL DEFAULT 1 COMMENT '乐观锁版本',
    COMMENT = '题目版本表';

ALTER TABLE question_options
    MODIFY id VARCHAR(140) NOT NULL COMMENT '题目选项关系ID',
    MODIFY question_version_id VARCHAR(64) NOT NULL COMMENT '题目版本ID',
    MODIFY option_id VARCHAR(64) NOT NULL COMMENT '选项ID',
    MODIFY option_label VARCHAR(500) NOT NULL COMMENT '选项展示文本',
    MODIFY option_order INT NOT NULL COMMENT '选项顺序',
    MODIFY created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    COMMENT = '单选题选项表';

ALTER TABLE attempts
    MODIFY id VARCHAR(64) NOT NULL COMMENT '作答ID',
    MODIFY exam_id VARCHAR(64) NOT NULL COMMENT '考试ID',
    MODIFY candidate_id VARCHAR(64) NOT NULL COMMENT '考生ID',
    MODIFY status VARCHAR(32) NOT NULL COMMENT '作答状态',
    MODIFY started_at TIMESTAMP(6) NOT NULL COMMENT '开始作答时间',
    MODIFY ends_at TIMESTAMP(6) NOT NULL COMMENT '作答截止时间',
    MODIFY submitted_at TIMESTAMP(6) NULL COMMENT '提交时间',
    MODIFY version BIGINT NOT NULL COMMENT '作答版本',
    MODIFY created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    MODIFY updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    COMMENT = '考生作答记录表';

ALTER TABLE answer_sheets
    MODIFY id VARCHAR(64) NOT NULL COMMENT '答卷ID',
    MODIFY attempt_id VARCHAR(64) NOT NULL COMMENT '作答ID',
    MODIFY status VARCHAR(32) NOT NULL COMMENT '答卷状态',
    MODIFY revision BIGINT NOT NULL COMMENT '答案修订版本',
    MODIFY updated_at TIMESTAMP(6) NOT NULL COMMENT '答卷最后更新时间',
    MODIFY submitted_at TIMESTAMP(6) NULL COMMENT '答卷提交时间',
    MODIFY created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    MODIFY version BIGINT NOT NULL DEFAULT 1 COMMENT '乐观锁版本',
    COMMENT = '答卷表';

ALTER TABLE answer_items
    MODIFY id VARCHAR(140) NOT NULL COMMENT '答案项ID',
    MODIFY answer_sheet_id VARCHAR(64) NOT NULL COMMENT '答卷ID',
    MODIFY question_id VARCHAR(64) NOT NULL COMMENT '题目业务ID',
    MODIFY type VARCHAR(32) NOT NULL COMMENT '答案题型',
    MODIFY selected_option_id VARCHAR(64) NULL COMMENT '单选题已选选项ID',
    MODIFY text_answer TEXT NULL COMMENT '简答题文本答案',
    MODIFY answer_order INT NOT NULL COMMENT '答案项顺序',
    MODIFY created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    COMMENT = '答卷答案项表';

ALTER TABLE submission_idempotency_records
    MODIFY idempotency_key VARCHAR(200) NOT NULL COMMENT '提交幂等键',
    MODIFY attempt_id VARCHAR(64) NOT NULL COMMENT '作答ID',
    MODIFY event_name VARCHAR(64) NOT NULL COMMENT '提交审计事件名称',
    MODIFY created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    COMMENT = '提交幂等记录表';
